on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "PP"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
      - uses: ./.github/actions/hello-docker
        id: hellodocker
        with:
          who-to-greet: "PP(from docker)"
      - run: |
          echo "Time: ${{ steps.hellodocker.outputs.time }}"
          echo $HELLO