name: CI
on:
  push:
    branches: [debug]
  

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules 
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - name: View file
        run: |
          cd .git/hooks
          cat pre-push.sample
          cat prepare-commit-msg.sample

 
     
